### ISSUE TITLE
#83 Nov Dec Talk and socialize

### ISSUE THREAD

**Issue by slashmili** [elixir-berlin/planning#70]
### Event URL

https://www.meetup.com/Elixir-Berlin/events/gdsglryccpbpb/

### Time

11th November 7pm CET

### Location

- [x] Remote

### Talks

- [x] "Domo library for automatic models validation in the microservice setting" by @IvanRublev
- [x]  "live view apps into Android + iOS" by @dominicletz

### TODO:
- [x] Update the Meetup event
- [x] Announce the event in twitter

**Comment by IvanRublev** [comment]
That’s good. I’m in!

**Comment by slashmili** [comment]
Could you both please join our Discord Server to discuss the details?

https://discord.gg/WaKTXHD
